export const colors = {
  beige: "#F5F5DC",
  ivory: "#FFFFF0",
  wheat: "#F5DEB3",
  lightYellow: "#FFFFE0",
  lavender: "#E6E6FA",
  mistyRose: "#FFE4E1",
  lightBlue: "#ADD8E6",
  lightPink: "#FFB6C1",
  lemonChiffon: "#FFFACD",
  paleGoldenrod: "#EEE8AA",
  cornsilk: "#FFF8DC",
  mintCream: "#F5FFFA",
  aliceBlue: "#F0F8FF",
  floralWhite: "#FFFAF0",
  honeydew: "#F0FFF0",
  oldLace: "#FDF5E6",
  seashell: "#FFF5EE",
  lightCyan: "#E0FFFF",
  lavenderBlush: "#FFF0F5",
  lightGoldenrodYellow: "#FAFAD2",
  papayaWhip: "#FFEFD5",
};
